	var character = $('[name="Character_Name"]').val();
	var level = $('[name="Character_Level"]').val();
	Class['name'] = $('[name="Class"]').val();
	Paragon = $('[name="Character_Path"]').val();
	Destiny = $('[name="Epic_Destiny"]').val();
	EXP = $('[name="Exp"]').val();
	Race['name'] = $('[name="Race"]').val();
	var size = $('[name="Size"]').val();
	var age = $('[name="Age"]').val();
	var gender = $('[name="Gender"]').val();
	var height = $('[name="Height"]').val();
	var weight = $('[name="Weight"]').val();
	var alignment = $('[name="Alignment"]').val();
	var diety = $('[name="Diety"]').val();
	var company = $('[name="Adventuring_company"]').val();